### ISSUE TITLE
大量Fixed-Cycle-Close-Connection线程TIMED_WAITING导致故障

### ISSUE THREAD

**Issue by yzpangu** [aliyun/HiTSDB-Client#23]
`Fixed-Cycle-Close-Connection - priority:5 - threadId:0x00007fbf60035800 - nativeId:0x30b - state:TIMED_WAITING
stackTrace:
java.lang.Thread.State: TIMED_WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x00000000b33365c8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)`

**Comment by hujianhong** [comment]
Sorry！这个Bug已经在最新版本中修复了；

<dependency>
    <groupId>com.aliyun</groupId>
    <artifactId>hitsdb-client</artifactId>
    <version>0.1.2</version>
</dependency>

**Comment by hujianhong** [comment]
Sorry! 这个Bug已经在最新版本中修复了
```
<!-- https://mvnrepository.com/artifact/com.aliyun/hitsdb-client -->
<dependency>
    <groupId>com.aliyun</groupId>
    <artifactId>hitsdb-client</artifactId>
    <version>0.1.2</version>
</dependency>
```

**Comment by yzpangu** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        ok,Thanks
    
        
            
        
    
    
        
            
        
    
    
          
        
            
    
        font{
            line-height: 1.6;
        }
    
李红红(盘古）研发中心   研发经理Tel：010-56163515Mob：+86-15001355938Add：北京市海淀区农大南路88号万霖大厦三层     邮编：100084   本电子邮件仅为指定收件人使用并可能载有保密内容。非指定收件人请勿使用、打开、转发、泄露、复印本电子邮件或依赖本邮件的内容而采取任何行动。若您误收到本电子邮件，请立即回复该电子邮件通知北京云纵信息技术有限公司，并请立即删除该电子邮件及其附件。谢谢！

        
    
     
    

    在2018年11月15日 11:41，胡建洪<notifications@github.com> 写道： 


Sorry! 这个Bug已经在最新版本中修复了

<dependency>
    <groupId>com.aliyun</groupId>
    <artifactId>hitsdb-client</artifactId>
    <version>0.1.2</version>
</dependency>
